package com.rohan.java8.methodreferences;

import java.util.Arrays;
import java.util.List;
import java.math.BigDecimal;


public class ObjectReference {
    public static void main(String[] args) {
        List<Employee> list = Arrays.asList(
                new Employee("mkyong", 38, BigDecimal.valueOf(3800)),
                new Employee("zilap", 5, BigDecimal.valueOf(100)),
                new Employee("ali", 25, BigDecimal.valueOf(2500)),
                new Employee("unknown", 99, BigDecimal.valueOf(9999)));

        ComparatorProvider c = new ComparatorProvider(); 
       list.sort(c::compareByName);
       System.out.println(list);
}
}
    
    class ComparatorProvider {

        public int compareByAge(Employee o1, Employee o2) {
            return o1.getAge().compareTo(o2.getAge());
        }

        public int compareByName(Employee o1, Employee o2) {
            return o1.getName().compareTo(o2.getName());
        }

        public int compareBySalary(Employee o1, Employee o2) {
            return o1.getAge().compareTo(o2.getAge());
        }

    }
    
    
    

    class Employee {

        public Employee(String string, int i, BigDecimal valueOf) {
			this.name = string;
			this.age = i;
			this.salary = valueOf;
		}
		String name;
        Integer age;
        BigDecimal salary;
        
        public Integer getAge() {
			return age;
		}
        public String getName() {
			return name;
		}
        public BigDecimal getSalary() {
			return salary;
		}
        
        @Override
        public String toString() {
        	// TODO Auto-generated method stub
        	return name;
        }

        // generated by IDE, getters, setters, constructor, toString
    }